tools: extract_kernel.py: Set default encoding to UTF-8
* Python uses ASCII as default encoding, which may causes decoding issue.
* For example: Our modina kernel is named with Japanese character, it will fail the build
  and give an error:

  Error: exited with code: 1
  Command: /bin/bash -c "build/make/tools/extract_kernel.py --tools lz4:out/host/linux-x86/bin/lz4  --input out/target/product/mona/kernel 	  --output-configs out/target/product/mona/obj/PACKAGING/check_vintf_all_intermediates/kernel_configs.txt 	  --output-release out/target/product/mona/obj/PACKAGING/check_vintf_all_intermediates/kernel_version.txt"
  Output:
  Cannot extract kernel kernel release in out/target/product/mona/kernel

* After reverted 5d323c17142bc9f3556a578342e06be0412901a4 an decoding error can be observed:
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 29: ordinal not in range(128).

* Set UTF-8 as default encoding to avoid it.